version: '3.8'

services:
  mongodb:
    image:mongo:6
    container_name:minimart_test_db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
    volumes:
      - mongo_test_data:/data/db

volumes:
  mongo_test_data: